version: '3.8'

services:
  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    container_name: symfony-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./symfony:/var/www
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/symfony

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/usr/src/app
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./symfony/public:/var/www/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
