name: Docker Compose CD

on:
  workflow_run:
    workflows: ["Docker Compose CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Backend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Pull Frontend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest

      - name: Stop and remove old Backend container
        run: |
          sudo docker stop task-management-app-backend-container || true
          sudo docker rm task-management-app-backend-container || true

      - name: Stop and remove old Frontend container
        run: |
          sudo docker stop task-management-app-frontend-container || true
          sudo docker rm task-management-app-frontend-container || true

      - name: Stop and remove old PostgreSQL container
        run: |
          sudo docker stop task-management-postgres || true
          sudo docker rm task-management-postgres || true

      - name: Stop and remove old Nginx container
        run: |
          sudo docker stop nginx-webserver || true
          sudo docker rm nginx-webserver || true

      - name: Run PostgreSQL container
        run: sudo docker run -d --name task-management-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=symfony -p 5432:5432 postgres:latest

      - name: Run Backend container
        run: sudo docker run -d --name task-management-app-backend-container --link task-management-postgres:postgres -e DATABASE_URL=postgresql://postgres:postgres@task-management-postgres:5432/symfony -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Run Frontend container
        run: sudo docker run -d --name task-management-app-frontend-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest

      - name: Run Nginx container
        run: sudo docker run -d --name nginx-webserver -p 80:80 nginx:alpine

      - name: Setup Nginx configuration
        run: |
          sudo docker exec nginx-webserver sh -c "echo 'server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://task-management-app-frontend-container:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection \"upgrade\";
                proxy_set_header Host \$host;
                proxy_cache_bypass \$http_upgrade;
            }

            location /api {
                proxy_pass http://task-management-app-backend-container:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection \"upgrade\";
                proxy_set_header Host \$host;
                proxy_cache_bypass \$http_upgrade;
            }
          }' > /etc/nginx/conf.d/default.conf"

      - name: Restart Nginx
        run: sudo docker exec nginx-webserver nginx -s reload
