name: Docker Compose CD

on:
  workflow_run:
    workflows: ["Docker Compose CI"]
    type:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Backend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Pull Frontend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest

      - name: Stop and remove old Backend container
        run: |
          sudo docker stop task-management-app-backend-container || true
          sudo docker rm task-management-app-backend-container || true

      - name: Stop and remove old Frontend container
        run: |
          sudo docker stop task-management-app-frontend-container || true
          sudo docker rm task-management-app-frontend-container || true

      - name: Run Backend container
        run: sudo docker run -d --name task-management-app-backend-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Run Frontend container
        run: sudo docker run -d --name task-management-app-frontend-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest
