name: Docker Compose CD

on:
  workflow_run:
    workflows: ["Docker Compose CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Backend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Pull Frontend Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest

      - name: Stop and remove old Backend container
        run: |
          sudo docker stop task-management-app-backend-container || true
          sudo docker rm task-management-app-backend-container || true

      - name: Stop and remove old Frontend container
        run: |
          sudo docker stop task-management-app-frontend-container || true
          sudo docker rm task-management-app-frontend-container || true

      - name: Stop and remove old PostgreSQL container
        run: |
          sudo docker stop task-management-postgres || true
          sudo docker rm task-management-postgres || true

      - name: Run PostgreSQL container
        run: sudo docker run -d --name task-management-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=symfony -p 5432:5432 postgres:latest

      - name: Run Backend container
        run: sudo docker run -d --name task-management-app-backend-container --link task-management-postgres:postgres -e DATABASE_URL=postgresql://postgres:postgres@task-management-postgres:5432/symfony -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Run Frontend container
        run: sudo docker run -d --name task-management-app-frontend-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest
