name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend (Symfony) image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest -f symfony/Dockerfile symfony/
          docker push ${{ secrets.DOCKER_USERNAME }}/task-management-app-backend:latest

      - name: Build and Push Frontend (Next.js) image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest -f nextjs/Dockerfile nextjs/
          docker push ${{ secrets.DOCKER_USERNAME }}/task-management-app-frontend:latest
